### PR TITLE
MIT License File added.

### PR DESCRIPTION
**Pull request by andykenward**
Need to add this to use on a project.

### CODE REVIEW

**Comment by ianmcgregor** [comment]
Hey sorry I missed this before. Licensed and legit now! Also have realised I should click the 'watch' button on my own repos (derp)

**Comment by andykenward** [comment]
No worries. I was checking if your asset-loader handled `svg`. But i doesnt seem to :( . Then I noticed my pull request :)

**Comment by ianmcgregor** [comment]
Ahh how would you handle SVG? Load as responseType text, put into a div outside of the dom and then return the SVG node?

**Comment by andykenward** [comment]
I started looking at [`preload.js`](https://github.com/CreateJS/PreloadJS/blob/master/src/preloadjs/loaders/SVGLoader.js) and how that handles SVG loading.

But I ended up just writing a quick react component, based on [`react-inlinesvg`](https://github.com/matthewwithanm/react-inlinesvg). Using [`whatwg-fetch`](https://github.com/github/fetch)  response text. 
https://gist.github.com/andykenward/db6031e7c53cd6e9c383823fadac0b9b

What you suggest makes sense to me.

**Pull request closed without merging**
